### ISSUE TITLE
"block-opening-brace-space-before" problem

### ISSUE THREAD

**Issue by meltifa** [mrmlnc/vscode-stylefmt#112]
i set "block-opening-brace-space-before": "always"

**before run stylefmt**
```scss
@at-root .content {
	padding-bottom: 20px;
}
```
**after run stylefmt**
```scss
@at-root .content{
	padding-bottom: 20px;
}
```
no space in opening brace before.
when i remove `@at-root`, it is work fine.
