### ISSUE TITLE
Does this extension support Allman style?

### ISSUE THREAD

**Issue by gusbemacbe** [mrmlnc/vscode-stylefmt#144]
### Environment

  * VSCode Version: 1.21.1
  * OS Version: macOS 10.13.3

Does this extension support Allman style? I would like to apply Allman style when I format CSS.

**Comment by mrmlnc** [comment]
Hello, @gusbemacbe,

I don't know what is «Allman» style. You can provide more detailed information about it?

**Comment by gusbemacbe** [comment]
For example:

Normal style:

```css
h1 { 
  color: red;
  font-family: "Din", sans-serif;
  font-size: 24px;
}
h2 { 
  color: green;
  font-family: "Din", sans-serif;
  font-size: 20px;
}

@media screen (max-width: 500px) {
	h1 { 
	  font-size: 20px;
	}
	h2 { 
	   font-size: 16px;
	}
}
```

Allman style:
```css
h1 
{ 
  color: red;
  font-family: "Din", sans-serif;
  font-size: 24px;
}

h2 
{ 
  color: green;
  font-family: "Din", sans-serif;
  font-size: 20px;
}

@media screen (max-width: 500px) 
{
   h1 
  { 
     font-size: 20px;
  }

   h1 
  { 
     font-size: 16px;
  }
}
```
